# Generated by Django 4.0 on 2022-01-03 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nmap', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NmapResult',
        ),
    ]
