# Generated by Django 4.0 on 2022-01-02 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nmap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nmapresult',
            name='host',
            field=models.TextField(default='unknown'),
            preserve_default=False,
        ),
    ]
